### ISSUE TITLE
Adapt to 0.7: A breaking change to onAfterUpdate is coming

### ISSUE THREAD

**Issue by aralroca** [siddharthborderwala/teaful-logger#1]
Thank you for your contributions 😊

I would like to comment that I was working with [this change]( https://github.com/aralroca/fragstore/pull/22) that would break a bit the logger operation and would have to be adapted: 

- https://github.com/aralroca/fragstore/pull/22

Looks that `path`, `value` and `prevValue` can be useful to log. The problem is that the `cart.price` can be executed with:

 ```js
const [,setCartPrice] = getStore.cart.price()
// setCartPrice(5)
const [,setCart] = getStore.cart()
// setCart(cart => ({ ...cart, price: 5 }))
const [,setStore] = getStore()
// setStore(store => ({ ...store, cart: { ...store.cart, price: 5 }}))
```

This means that **`path`** can be `cart.price`, `cart` or ` `. **`value`** can be `5`, `{ items: [], price: 5 }` or `{ username: '', cart: { items: [], price 5 } }`. And the same for **`prevValue`**.

I gave this a lot of thought to improve it to make it easier to use. And the conclusion I came to is to return only **`store`** and **`prevStore`**.

So with this PR, instead of:

```js
const { getStore } = createStore(initialStore, onAfterUpdate)

function onAfterUpdate({ path, value, prevValue }) {
  if(path === 'cart.price' || path === 'cart' || !path) {
     const price = value?.cart?.price || value?.price || value
     const [,setErrorMsg] = getStore.errorMsg()
     setErrorMsg(price > 99 ? 'price should be lower than $99' : '')
   }
}
```

will be:

```js
const { getStore } = createStore(initialStore, onAfterUpdate)

function onAfterUpdate({ store, prevStore }) {
  if(store.cart.price !== prevStore.cart.price) {
     const { price } = store.cart
     const [,setErrorMsg] = getStore.errorMsg()
     setErrorMsg(price > 99 ? 'price should be lower than $99' : '')
   }
}
```

It will be a bit groundbreaking but it will simplify a number of things. For the log, maybe you can use a library like [json-diff](https://github.com/andreyvit/json-diff):

![Screenshot](https://github.com/andreyvit/json-diff/raw/master/doc/screenshot.png)

I don't know how well it will perform, though 😕

How do you see the change to be made in 0.7?  🤔 As my PR is still open without being merged, if you come up with an idea that could improve the logs, like adding the path field again, we could discuss it.

Thanks again 🤗

**Comment by siddharthborderwala** [comment]
I think you have solid reasons to change the signature of the onAfterUpdate function, and I think that it does simplify things. So, I'll update the logger library according to the 0.7 version, and thank you for your feedback!

**Comment by siddharthborderwala** [comment]
Addressed
